<a href="https://colab.research.google.com/github/SSaiTeja23/SAITEJA_INFO5731_SPRING2020/blob/master/Copy_of_In_class_exercise_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **The second In-class-exercise**


(1) Write a Python program to find the duplicate elements in a given array of integers. Return -1 If there are no such elements.

In [0]:
# write your answer here
def Duplicates(list1): 
    dict = {} 
    count=0
  
    for ele in list1: 
        try: 
            dict[ele] += 1
        except: 
            dict[ele] = 1
              
    for item in dict: 

        if(dict[item] > 1): 
            count = count+1
           # a=a+1
            print(item, end=" ")

    if(count==0):
      return -1 
  
    print("\n")

list2 = [6, 12, 11, 5, 12] 
Duplicates(list2)



12 



(2) Write a Python program to select all the Sundays of a specified year.



In [0]:
# write your answer here
from datetime import date, timedelta

def all_sundays(year):
# January 1st of the given year
       date1 = date(year, 1, 1)
# First Sunday of the given year       
       date1 += timedelta(days = 6 - date1.weekday())  
       while date1.year == year:
          yield date1
          date1 += timedelta(days = 7)
          
for s in all_sundays(2020):
   print(s)



2020-01-05
2020-01-12
2020-01-19
2020-01-26
2020-02-02
2020-02-09
2020-02-16
2020-02-23
2020-03-01
2020-03-08
2020-03-15
2020-03-22
2020-03-29
2020-04-05
2020-04-12
2020-04-19
2020-04-26
2020-05-03
2020-05-10
2020-05-17
2020-05-24
2020-05-31
2020-06-07
2020-06-14
2020-06-21
2020-06-28
2020-07-05
2020-07-12
2020-07-19
2020-07-26
2020-08-02
2020-08-09
2020-08-16
2020-08-23
2020-08-30
2020-09-06
2020-09-13
2020-09-20
2020-09-27
2020-10-04
2020-10-11
2020-10-18
2020-10-25
2020-11-01
2020-11-08
2020-11-15
2020-11-22
2020-11-29
2020-12-06
2020-12-13
2020-12-20
2020-12-27


(3) Python files reading and writing. Download the “[exercise_02_data _collection.zip](https://github.com/unt-iialab/INFO5731_Spring2020/blob/master/In_class_exercise/exercise_02_data_collection.zip)” to your local and un-zip it.

*   Write a program to read all the txt files and save the sentences in all the files into one csv file with two columns, the first column is sentence id (txt file name+sentence line number), the second column is the sentence text content.
*   Remove all the punctuations from the sentences, save the processed sentences into a new column in the same csv file.
*   Ask the user to enter a word, return all the sentences that include this word, three kinds of information should be returned: sentence id, sentence text content, the count that user input word appear in the sentence..



In [0]:
# write your answer here
import os
from google.colab import files
uploaded = files.upload()





Saving ARTHROTEC.1.txt to ARTHROTEC.1 (1).txt
Saving ARTHROTEC.2.txt to ARTHROTEC.2 (1).txt
Saving ARTHROTEC.3.txt to ARTHROTEC.3 (1).txt
Saving ARTHROTEC.4.txt to ARTHROTEC.4 (1).txt
Saving ARTHROTEC.5.txt to ARTHROTEC.5 (1).txt
Saving ARTHROTEC.6.txt to ARTHROTEC.6 (1).txt
Saving ARTHROTEC.7.txt to ARTHROTEC.7 (1).txt
Saving ARTHROTEC.8.txt to ARTHROTEC.8 (1).txt
Saving ARTHROTEC.9.txt to ARTHROTEC.9 (1).txt
Saving ARTHROTEC.10.txt to ARTHROTEC.10 (1).txt
Saving ARTHROTEC.11.txt to ARTHROTEC.11 (1).txt
Saving ARTHROTEC.12.txt to ARTHROTEC.12 (1).txt
Saving ARTHROTEC.13.txt to ARTHROTEC.13 (1).txt
Saving ARTHROTEC.14.txt to ARTHROTEC.14 (1).txt
Saving ARTHROTEC.15.txt to ARTHROTEC.15 (1).txt
Saving ARTHROTEC.16.txt to ARTHROTEC.16 (1).txt
Saving ARTHROTEC.17.txt to ARTHROTEC.17 (1).txt
Saving ARTHROTEC.18.txt to ARTHROTEC.18 (1).txt
Saving ARTHROTEC.19.txt to ARTHROTEC.19 (1).txt
Saving ARTHROTEC.20.txt to ARTHROTEC.20 (1).txt
Saving ARTHROTEC.21.txt to ARTHROTEC.21 (1).txt
Saving ART

In [0]:
import pandas as pd
import csv
col_id=[]
out=[]
new_list=[]
sentences=[]
for file in uploaded:
  with open(file, 'r') as f:
     text = f.read()
     sentences=text.splitlines()
     length=len(sentences)
     for j in range(length):
       col_id.append(file+'.'+str(j))
     for i in sentences:
       out.append(i)
with open('output.csv', 'w') as f:
    writer = csv.writer(f)
    for val in out:
        writer.writerow([val])
data1= pd.read_csv("output.csv",names=['text'])
data2= pd.DataFrame(col_id,columns=['Sentence_ID']) 
result = pd.concat([data1,data2],axis=1)
#result['Sentence_ID','text']
result = result.reindex(columns=['Sentence_ID','text'])
result.to_csv('Final.csv')
#check output in csv file generated

In [0]:
result["No_Punctuation"] = result['text'].str.replace('[^\w\s]','')
result

Sentence_ID  ...                                     No_Punctuation
0      ARTHROTEC.1.txt.0  ...  I feel a bit drowsy  have a little blurred vis...
1      ARTHROTEC.1.txt.1  ...  Ive been on Arthrotec 50 for over 10 years on ...
2      ARTHROTEC.1.txt.2  ...  Due to my arthritis getting progressively wors...
3      ARTHROTEC.1.txt.3  ...  every day for the next month to see how I get ...
4      ARTHROTEC.1.txt.4  ...  So far its been very good pains almost gone bu...
..                   ...  ...                                                ...
530  ARTHROTEC.100.txt.3  ...                           canker sores in my mouth
531  ARTHROTEC.100.txt.4  ...                                           headache
532  ARTHROTEC.100.txt.5  ...            been off for 1 week still have bleeding
533  ARTHROTEC.100.txt.6  ...                               helped my pain alot 
534  ARTHROTEC.100.txt.7  ...                 too scared to take this drug again

[535 rows x 3 columns]

(4) Install packages nltk, numpy, scipy, pandas, and sklearn on Google Colab. Write a program to test whether they are installed successfully. 

In [0]:
# write your answer here
import nltk
nltk.download()




NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> all
       | 
       | Downloading package abc to /root/nltk_data...
       |   Unzipping corpora/abc.zip.
       | Downloading package alpino to /root/nltk_data...
       |   Unzipping corpora/alpino.zip.
       | Downloading package biocreative_ppi to /root/nltk_data...
       |   Unzipping corpora/biocreative_ppi.zip.
       | Downloading package brown to /root/nltk_data...
       |   Unzipping corpora/brown.zip.
       | Downloading package brown_tei to /root/nltk_data...
       |   Unzipping corpora/brown_tei.zip.
       | Downloading package cess_cat to /root/nltk_data...
       |   Unzipping corpora/cess_cat.zip.
       | Downloading package cess_esp to /root/nltk_data...
 

True

In [0]:
pip install nltk

In [0]:
from nltk.tokenize import sent_tokenize, word_tokenize
EXAMPLE_TEXT = "Hello world, what's up?, How are you doin? , Data Science is boom"
print(sent_tokenize(EXAMPLE_TEXT))

["Hello world, what's up?, How are you doin?", ', Data Science is boom']


In [0]:
pip install numpy;

In [0]:
import numpy as np 
a = np.array([[1, 2], 
			[3, 4]]) 
b = np.array([[5, 6], 
			[7, 8]]) 
print ("Array sum:\n", a + b) 
print ("Array multiplication:\n", a*b) 
print ("Matrix multiplication:\n", a.dot(b))

Array sum:
 [[ 6  8]
 [10 12]]
Array multiplication:
 [[ 5 12]
 [21 32]]
Matrix multiplication:
 [[19 22]
 [43 50]]


In [0]:
pip install scipy

In [0]:
from scipy.special import cbrt
cb = cbrt([8, 125])
print(cb)

[2. 5.]


In [0]:
pip install pandas

In [0]:
import pandas as pd
df = pd.DataFrame({'X':[21,22,23,24,25], 'Y':[10,11,12,13,14],'Z':[41,42,43,44,45]});
print(df)

    X   Y   Z
0  21  10  41
1  22  11  42
2  23  12  43
3  24  13  44
4  25  14  45


In [0]:
pip install scikit-learn

In [0]:
from sklearn import datasets
iris= datasets.load_iris()
print(iris.data.shape)

(150, 4)
